"""Helpers for discovering replay sessions generated by the integrated telemetry loader."""

from __future__ import annotations

from pathlib import Path
from typing import Any

try:
    from ..open_pit_wall.data_loader import get_computed_data_directory
    from ..open_pit_wall.telemetry_broadcaster import load_replay_session
except ImportError:
    from open_pit_wall.data_loader import get_computed_data_directory
    from open_pit_wall.telemetry_broadcaster import load_replay_session


def list_replay_sessions() -> list[dict[str, Any]]:
    """Return metadata for valid replay JSON files in the shared replay directory."""

    sessions: list[dict[str, Any]] = []
    replay_directory = get_computed_data_directory()
    for path in sorted(replay_directory.glob("*.json")):
        try:
            replay = load_replay_session(path)
        except (OSError, TypeError, ValueError):
            continue

        sessions.append(
            {
                "file": path.name,
                "path": str(path),
                "schema_version": replay.schema_version,
                "duration_seconds": replay.duration_seconds,
                "total_laps": replay.total_laps,
                "driver_codes": replay.driver_codes,
                "race_control_messages": len(replay.race_control_messages),
            }
        )
    return sessions


def get_replay_directory() -> Path:
    """Return the shared directory used for generated replay files."""

    return get_computed_data_directory()
