"""Routes for the integrated historical telemetry replay utility."""

from __future__ import annotations

from fastapi import APIRouter

try:
    from ..services.replay_service import get_replay_directory, list_replay_sessions
except ImportError:
    from services.replay_service import get_replay_directory, list_replay_sessions

router = APIRouter(prefix="/api/v1/replay", tags=["replay"])


@router.get("/sessions")
async def get_replay_sessions() -> dict:
    """List replay sessions generated by the bundled telemetry loader."""

    return {
        "replay_directory": str(get_replay_directory()),
        "sessions": list_replay_sessions(),
    }
